name: list-of-films-django

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set Up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: "Install dependencies"
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Run tests"
        run: python manage.py test films

  deploy:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'list-of-films-django'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          env_file: ".env"
